title : The Machine Learning Simplified book
author: Andrew Wolf
logo: _static/img/mls_logo.png

# Short description about the book
description: >-
   Supplement to the 'Machine Learning Simplified: A Gentle Introduction to Supervised Learning' book.
repository:
  url                       : https://github.com/5x12/themlsbook
  path_to_book              : jupyter_book
  branch: master            # Which branch of the repository should be used when creating links (optional)

execute:
  execute_notebooks           : cache
  timeout: -1

# exclude some content
exclude_patterns: ["book/ignore/*", "Readme.md"]

# HTML-specific settings
html:
  favicon                     : _static/img/favicon.ico
  home_page_in_navbar         : true  # Whether to include your home page in the left Navigation Bar
  use_edit_page_button        : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button       : true  # Whether to add a link to your repository button
  use_issues_button           : true  # Whether to add an "open an issue" button

# Interact link settings
notebook_interface            : "notebook"

sphinx:
  config:
    html_extra_path: ["."]
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
      - https://c6.patreon.com/becomePatronButton.bundle.js